export interface F1Race {
  id: string
  round: number
  name: string
  circuit: string
  location: string
  country: string
  date: string
  time: string
  timezone: string
  isSprint: boolean
  liveStreamOptions: {
    f1tv: string
    espn?: string
    skyf1?: string
    free?: string[]
  }
}

export const f1Schedule2025: F1Race[] = [
  {
    id: "australia-gp-2025",
    round: 1,
    name: "Australian Grand Prix",
    circuit: "Albert Park Circuit",
    location: "Melbourne",
    country: "Australia",
    date: "2025-03-16",
    time: "15:00",
    timezone: "GMT+11",
    isSprint: false,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
    },
  },
  {
    id: "china-gp-2025",
    round: 2,
    name: "Chinese Grand Prix",
    circuit: "Shanghai International Circuit",
    location: "Shanghai",
    country: "China",
    date: "2025-03-23",
    time: "15:00",
    timezone: "GMT+8",
    isSprint: true,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
    },
  },
  {
    id: "japan-gp-2025",
    round: 3,
    name: "Japanese Grand Prix",
    circuit: "Suzuka International Racing Course",
    location: "Suzuka",
    country: "Japan",
    date: "2025-04-06",
    time: "15:00",
    timezone: "GMT+9",
    isSprint: false,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
    },
  },
  {
    id: "bahrain-gp-2025",
    round: 4,
    name: "Bahrain Grand Prix",
    circuit: "Bahrain International Circuit",
    location: "Sakhir",
    country: "Bahrain",
    date: "2025-04-13",
    time: "15:00",
    timezone: "GMT+3",
    isSprint: false,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
      free: ["Channel 4 (UK highlights)"],
    },
  },
  {
    id: "saudi-arabia-gp-2025",
    round: 5,
    name: "Saudi Arabian Grand Prix",
    circuit: "Jeddah Corniche Circuit",
    location: "Jeddah",
    country: "Saudi Arabia",
    date: "2025-04-20",
    time: "17:00",
    timezone: "GMT+3",
    isSprint: false,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
    },
  },
  {
    id: "miami-gp-2025",
    round: 6,
    name: "Miami Grand Prix",
    circuit: "Miami International Autodrome",
    location: "Miami",
    country: "United States",
    date: "2025-05-04",
    time: "15:30",
    timezone: "GMT-4",
    isSprint: true,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      free: ["ABC (USA live coverage)"],
    },
  },
  {
    id: "emilia-romagna-gp-2025",
    round: 7,
    name: "Emilia Romagna Grand Prix",
    circuit: "Autodromo Enzo e Dino Ferrari",
    location: "Imola",
    country: "Italy",
    date: "2025-05-18",
    time: "15:00",
    timezone: "GMT+2",
    isSprint: false,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
    },
  },
  {
    id: "monaco-gp-2025",
    round: 8,
    name: "Monaco Grand Prix",
    circuit: "Circuit de Monaco",
    location: "Monte Carlo",
    country: "Monaco",
    date: "2025-05-25",
    time: "15:00",
    timezone: "GMT+2",
    isSprint: false,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
      free: ["Channel 4 (UK live coverage)"],
    },
  },
  {
    id: "spain-gp-2025",
    round: 9,
    name: "Spanish Grand Prix",
    circuit: "Circuit de Barcelona-Catalunya",
    location: "Barcelona",
    country: "Spain",
    date: "2025-06-01",
    time: "15:00",
    timezone: "GMT+2",
    isSprint: false,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
    },
  },
  {
    id: "canada-gp-2025",
    round: 10,
    name: "Canadian Grand Prix",
    circuit: "Circuit Gilles Villeneuve",
    location: "Montreal",
    country: "Canada",
    date: "2025-06-15",
    time: "14:00",
    timezone: "GMT-4",
    isSprint: false,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
    },
  },
  {
    id: "austria-gp-2025",
    round: 11,
    name: "Austrian Grand Prix",
    circuit: "Red Bull Ring",
    location: "Spielberg",
    country: "Austria",
    date: "2025-06-29",
    time: "15:00",
    timezone: "GMT+2",
    isSprint: false,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
    },
  },
  {
    id: "britain-gp-2025",
    round: 12,
    name: "British Grand Prix",
    circuit: "Silverstone Circuit",
    location: "Silverstone",
    country: "United Kingdom",
    date: "2025-07-06",
    time: "15:00",
    timezone: "GMT+1",
    isSprint: false,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
      free: ["Channel 4 (UK live coverage)"],
    },
  },
  {
    id: "belgium-gp-2025",
    round: 13,
    name: "Belgian Grand Prix",
    circuit: "Circuit de Spa-Francorchamps",
    location: "Spa",
    country: "Belgium",
    date: "2025-07-27",
    time: "15:00",
    timezone: "GMT+2",
    isSprint: true,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
      free: ["RTBF (Belgium live coverage)"],
    },
  },
  {
    id: "hungary-gp-2025",
    round: 14,
    name: "Hungarian Grand Prix",
    circuit: "Hungaroring",
    location: "Budapest",
    country: "Hungary",
    date: "2025-08-03",
    time: "15:00",
    timezone: "GMT+2",
    isSprint: false,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
    },
  },
  {
    id: "netherlands-gp-2025",
    round: 15,
    name: "Dutch Grand Prix",
    circuit: "Circuit Zandvoort",
    location: "Zandvoort",
    country: "Netherlands",
    date: "2025-08-31",
    time: "15:00",
    timezone: "GMT+2",
    isSprint: false,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
    },
  },
  {
    id: "italy-gp-2025",
    round: 16,
    name: "Italian Grand Prix",
    circuit: "Autodromo Nazionale di Monza",
    location: "Monza",
    country: "Italy",
    date: "2025-09-07",
    time: "15:00",
    timezone: "GMT+2",
    isSprint: false,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
    },
  },
  {
    id: "azerbaijan-gp-2025",
    round: 17,
    name: "Azerbaijan Grand Prix",
    circuit: "Baku City Circuit",
    location: "Baku",
    country: "Azerbaijan",
    date: "2025-09-21",
    time: "13:00",
    timezone: "GMT+4",
    isSprint: false,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
    },
  },
  {
    id: "singapore-gp-2025",
    round: 18,
    name: "Singapore Grand Prix",
    circuit: "Marina Bay Street Circuit",
    location: "Singapore",
    country: "Singapore",
    date: "2025-10-05",
    time: "20:00",
    timezone: "GMT+8",
    isSprint: false,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
    },
  },
  {
    id: "usa-gp-2025",
    round: 19,
    name: "United States Grand Prix",
    circuit: "Circuit of the Americas",
    location: "Austin",
    country: "United States",
    date: "2025-10-19",
    time: "14:00",
    timezone: "GMT-5",
    isSprint: true,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      free: ["ABC (USA live coverage)"],
    },
  },
  {
    id: "mexico-gp-2025",
    round: 20,
    name: "Mexican Grand Prix",
    circuit: "Autodromo Hermanos Rodriguez",
    location: "Mexico City",
    country: "Mexico",
    date: "2025-10-26",
    time: "14:00",
    timezone: "GMT-6",
    isSprint: false,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
    },
  },
  {
    id: "brazil-gp-2025",
    round: 21,
    name: "Brazilian Grand Prix",
    circuit: "Autodromo Jose Carlos Pace",
    location: "São Paulo",
    country: "Brazil",
    date: "2025-11-09",
    time: "14:00",
    timezone: "GMT-3",
    isSprint: true,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
    },
  },
  {
    id: "las-vegas-gp-2025",
    round: 22,
    name: "Las Vegas Grand Prix",
    circuit: "Las Vegas Strip Circuit",
    location: "Las Vegas",
    country: "United States",
    date: "2025-11-22",
    time: "22:00",
    timezone: "GMT-8",
    isSprint: false,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      free: ["ABC (USA live coverage)"],
    },
  },
  {
    id: "qatar-gp-2025",
    round: 23,
    name: "Qatar Grand Prix",
    circuit: "Losail International Circuit",
    location: "Lusail",
    country: "Qatar",
    date: "2025-11-30",
    time: "16:00",
    timezone: "GMT+3",
    isSprint: true,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
    },
  },
  {
    id: "abu-dhabi-gp-2025",
    round: 24,
    name: "Abu Dhabi Grand Prix",
    circuit: "Yas Marina Circuit",
    location: "Abu Dhabi",
    country: "United Arab Emirates",
    date: "2025-12-07",
    time: "17:00",
    timezone: "GMT+4",
    isSprint: false,
    liveStreamOptions: {
      f1tv: "https://f1tv.formula1.com",
      espn: "https://www.espn.com/f1/",
      skyf1: "https://www.skysports.com/f1",
    },
  },
]
